# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
logging:
  config: classpath:logback-spring.xml
  file: micro-web.log
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework: INFO
  path: /var/log
# spring.profiles.activeにデフォルトでアクティブなプロファイルを指定
spring:
  application:
    name: web
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  profiles:
    active: dev
    #    active: production
    #    active: test
    include: message
