# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
spring:
  aop:
    auto: true
  beaninfo:
    ignore: true
  data:
    jpa:
      repositories:
        enabled: true
    rest:
      base-path: /
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
  info:
    build:
      location: classpath:META-INF/build-info.properties
    git:
      location: classpath:git.properties
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
logging:
  config: classpath:logback-spring.xml
  file: micro-api.log
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework: INFO
  path: /var/log

