# Docker Engine 18.06.0+
version: '3.7'

services:

  nginx:
    container_name: container_nginx
    hostname: container_nginx_hostname
    build: ./docker-nginx
    ports:
      - 80:8080
    restart: always

  mysqlRc:
    image: mysql:8.0.16
    container_name: mysqlRc
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf/:/etc/mysql/conf.d
    networks:
      - sonarnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      TZ: "Asia/Tokyo"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysqlRc
    ports:
      - 8280:80
    volumes:
      - /sessions
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysqlRc
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always

  sonarqube:
    image: sonarqube:7.7-community
    container_name: sonarqube
    depends_on:
      - mysqlRc
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonarnet
    command: -Dsonar.web.context=/sonar
    ports:
      - 9000:9000
      - 9092:9092
    environment:
      - SONAR_JDBC_URL=jdbc:mysql://localhost:3306/sonar?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    restart: always

networks:
  sonarnet:
    driver: bridge
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins: