# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
spring:
  cloud:
    config:
      uri: http://localhost:9000/SudokuConfig/
      name: application
      profile: api_a
  profiles: dev