# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
banner:
  charset: UTF-8
  location: classpath:banner.txt

# ----------------------------------------
# LOGGING PROPERTIES
# ----------------------------------------
logging:
  config: classpath:logback-spring.xml
  file: micro-api.log
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework: INFO
  path: /var/log
# spring.profiles.activeにデフォルトでアクティブなプロファイルを指定
spring:
  profiles:
    active: dev
    #    active: production
    #    active: test
    include: message
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/ # default
  main:
    allow-bean-definition-overriding: true

